spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bambino?useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false