spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bambino?useSSL=false
    username: root
    password: S4nt4T3ch2017
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  mail:
    host: smtp.gmail.com
    port: 465
    #username: santatechalv@gmail.com
    #password: S4nt4t3ch
    username: rogerdavila.stech@gmail.com
    password: S4nt4T3chn0l0gy2017
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
logging:
  level:
    ROOT: INFO,ERROR
    org: 
      springframework:
        web: ERROR
    com:
      bambinocare: INFO,ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file: /home/rogerdavila/logs/bambinocare/application.log
   
   